spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  cloud:
    config.server.git:
      uri: file:///C:/dev/braintrain-config-repo
      clone-on-start: true
  security.user:
    name: root
    password: s3cr3t

server:
  port: 8089

